tentative 1

diff --git a/ping/pipelines.steps.yml b/ping/pipelines.steps.yml
--- a/ping/pipelines.steps.yml
+++ b/ping/pipelines.steps.yml
@@ -34,6 +34,9 @@ pipelines:
             {{- end }}
             iteration: 2
             sleepBetweenIteration: 5
+          execution:
+            onComplete:
+              - echo ${mainHeartBeat}
         - name: Update_status_yml
           type: Bash
           configuration:
@@ -50,6 +53,7 @@ pipelines:
             {{- end }}
           execution:
             onStart:
+              - echo ${mainHeartBeat}
               - echo "Ping_2 status = ${step_Ping_2_statusName}"
               - saas_dr=$(echo {{ .Values.jpdIntegrationName }} | cut -d" " -f2 | tr -d ])
               - url="int_${saas_dr}_url"
@@ -60,5 +64,22 @@ pipelines:
               - jf rt ping
               - curl -L https://github.com/mikefarah/yq/releases/download/v4.27.5/yq_linux_amd64 -o yq && chmod +x yq && ./yq -V
             onExecute:
-              - jf rt dl jfrog-automation/status.yml .
- 
+              - exists=$(jf rt dl jfrog-automation/status.yml . | jq -r ."totals"."success")
+              - |
+                if [[ $exists -eq 1 ]]; then 
+                  echo "[INFO] status.yml found"; 
+                  hb=[[ ${step_Ping_2_statusName} == "success" ]] && echo "1000"
+                else 
+                  echo "[INFO] status.yml NOT found ... initializing it ...";
+                  touch status.yml
+                  ./yq -e -i .from=SAAS_DR status.yml
+                  ./yq -e -i .to=SAAS_MAIN status.yml
+                  hb=[[ ${step_Ping_2_statusName} == "success" ]] && echo "1000" || echo "0"
+                fi
+              - canUpdateDR=[[ ${step_Ping_2_statusName} == "success" ]] && echo "true" || echo "false"
+              - epochNow=$(date +%s)
+              - props="from=SAAS_DR;to=SAAS_MAIN;canUpdateDR=${canUpdateDR};lastHearBeatFromMain=${hb};requestDateTime=${epochNow}"
+              - ./yq -e -i .canUpdateDR=${canUpdateDR} status.yml 
+              - ./yq -e -i .lastHearBeatFromMain=${hb} status.yml 
+              - ./yq -e -i .requestDateTime=${epochNow} status.yml 
+              - jf rt u status.yml jfrog-automation/ --target-props $props
