quick fix 8

diff --git a/ping/pipelines.steps.yml b/ping/pipelines.steps.yml
--- a/ping/pipelines.steps.yml
+++ b/ping/pipelines.steps.yml
@@ -11,7 +11,7 @@ pipelines:
           type: Bash
           configuration:
             integrations:
-              - name: yann_platform_token
+              - name: {{ .Values.jpdIntegrationName }}
           execution:
             onStart:
               - echo {{ .Values.jpdIntegrationName }}
@@ -23,12 +23,11 @@ pipelines:
                 do 
                     echo "[INFO] iteration $i ..."
                     jf rt ping --server-id psemea
-                    if [ $? -eq 0 ]; then
-                      echo "[INFO] iteration $i : OK"
-                    else
-                      echo "[ERROR] iteration $i : KO"
-                    fi
                     sleep 5
                 done
 
-         
+                    #          if [ $? -eq 0 ]; then
+                    #   echo "[INFO] iteration $i : OK"
+                    # else
+                    #   echo "[ERROR] iteration $i : KO"
+                    # fi
