[sync] debug 1

diff --git a/sync/pipelines.steps.yml b/sync/pipelines.steps.yml
--- a/sync/pipelines.steps.yml
+++ b/sync/pipelines.steps.yml
@@ -50,16 +50,18 @@ pipelines:
               if [[ $exists -eq 1 ]]; then 
                 echo "[INFO] {{ .Values.statusFile }} found"; 
                 canUpdateDR=$(jf rt curl "/api/storage/{{ .Values.automationRepo }}/{{ .Values.statusFile }}?properties=canUpdateDR" | jq -r ".properties.canUpdateDR[]")
+                echo $canUpdateDR
                 requestDateTime=$(jf rt curl "/api/storage/{{ .Values.automationRepo }}/{{ .Values.statusFile }}?properties=requestDateTime" | jq -r ".properties.requestDateTime[]")
+                echo $requestDateTime
               else 
                 echo "[WARN] {{ .Values.statusFile }} NOT found. Check if the Health Check pipeline has run on the DR side"
                 exit 1
               fi
-            - |
-              if [[ $epochNow - $requestDateTime > {{ .Values.HealthCheckIntervalInSec }} ]] ; then 
-                  echo "[ERROR] the last update on the  {{ .Values.automationRepo }}/{{ .Values.statusFile }} was more than {{ .Values.HealthCheckIntervalInSec }} seconds."
-                  exit 1
-              fi 
+            # - |
+            #   if [[ $epochNow - $requestDateTime > {{ .Values.HealthCheckIntervalInSec }} ]] ; then 
+            #       echo "[ERROR] the last update on the  {{ .Values.automationRepo }}/{{ .Values.statusFile }} was more than {{ .Values.HealthCheckIntervalInSec }} seconds."
+            #       exit 1
+            #   fi 
             - |
               if [[ $canUpdateDR -eq "false" ]] ; then
                   echo "[WARN] File {{ .Values.automationRepo }}/{{ .Values.statusFile }} : canUpdateDR=false; No sync will be pushed to the DR."
